# Generated by Django 3.2 on 2024-10-30 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20241030_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='offer_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
