# Generated by Django 3.2 on 2024-10-30 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_offer_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='offer_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='入职时间'),
        ),
    ]
