# Generated by Django 3.2 on 2024-10-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deparment',
            new_name='Department',
        ),
    ]
