# Generated by Django 3.2 on 2024-10-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
